
#ifndef THORIUM_CONFIGURATION_H
#define THORIUM_CONFIGURATION_H

#define THORIUM_NODE_MAXIMUM_RECEIVED_MESSAGE_COUNT_PER_CALL 8
#define THORIUM_NODE_MAXIMUM_SENT_MESSAGE_COUNT_PER_CALL 8

/*
 * In nanoseconds
 */
#define THORIUM_MULTIPLEXER_TIMEOUT 200000

#endif
