
APPLICATION_TRANSPORT_TESTER_PRODUCT=applications/transport_tester/transport_tester
APPLICATION_TRANSPORT_TESTER_OBJECTS=applications/transport_tester/main.o applications/transport_tester/process.o

APPLICATION_EXECUTABLES+=$(APPLICATION_TRANSPORT_TESTER_PRODUCT)
APPLICATION_OBJECTS+=$(APPLICATION_TRANSPORT_TESTER_OBJECTS)

$(APPLICATION_TRANSPORT_TESTER_PRODUCT): $(APPLICATION_TRANSPORT_TESTER_OBJECTS) $(LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)

