
#ifndef _BSAL_CONSTANTS_H
#define _BSAL_CONSTANTS_H

/* event counters */

#define BSAL_EVENT_COUNTER_RECEIVED_MESSAGES 0
#define BSAL_EVENT_COUNTER_RECEIVED_MESSAGES_SAME_NODE 1
#define BSAL_EVENT_COUNTER_RECEIVED_MESSAGES_OTHER_NODE 2
#define BSAL_EVENT_COUNTER_SENT_MESSAGES 3
#define BSAL_EVENT_COUNTER_SENT_MESSAGES_SAME_NODE 4
#define BSAL_EVENT_COUNTER_SENT_MESSAGES_OTHER_NODE 5

#endif
