
#ifndef _BSAL_CONSTANTS_H
#define _BSAL_CONSTANTS_H

#define BSAL_DEFAULT_COUNT 32

/* engine/actor.h */
#define BSAL_TAG_OFFSET_ACTOR 0
#define BSAL_TAG_COUNT_ACTOR BSAL_DEFAULT_COUNT

/* input/input_stream.h */
#define BSAL_TAG_OFFSET_INPUT_STREAM ( BSAL_TAG_OFFSET_ACTOR + BSAL_TAG_COUNT_ACTOR )
#define BSAL_TAG_COUNT_INPUT_STREAM BSAL_DEFAULT_COUNT

/* input/input_controller.h */
#define BSAL_TAG_OFFSET_INPUT_CONTROLLER ( BSAL_TAG_OFFSET_INPUT_STREAM+ BSAL_TAG_COUNT_INPUT_STREAM)
#define BSAL_TAG_COUNT_INPUT_CONTROLLER BSAL_DEFAULT_COUNT

/* storage/graph_store.h */
#define BSAL_TAG_OFFSET_GRAPH_STORE (BSAL_TAG_OFFSET_INPUT_STREAM + BSAL_TAG_COUNT_INPUT_STREAM)
#define BSAL_TAG_COUNT_GRAPH_STORE BSAL_DEFAULT_COUNT

/* storage/sequence_store.h */
#define BSAL_TAG_OFFSET_SEQUENCE_STORE (BSAL_TAG_OFFSET_GRAPH_STORE + BSAL_TAG_COUNT_GRAPH_STORE)
#define BSAL_TAG_COUNT_SEQUENCE_STORE BSAL_DEFAULT_COUNT

/* the user can start with this value */
#define BSAL_TAG_OFFSET_USER ( BSAL_TAG_OFFSET_INPUT_STREAM + BSAL_TAG_COUNT_INPUT_STREAM )

/* counters */

#define BSAL_COUNTER_RECEIVED_MESSAGES 0
#define BSAL_COUNTER_RECEIVED_MESSAGES_SAME_NODE 1
#define BSAL_COUNTER_RECEIVED_MESSAGES_OTHER_NODE 2
#define BSAL_COUNTER_SENT_MESSAGES 3
#define BSAL_COUNTER_SENT_MESSAGES_SAME_NODE 4
#define BSAL_COUNTER_SENT_MESSAGES_OTHER_NODE 5

#endif
