TEST_ASSEMBLY_ARC_NAME=assembly_arc
TEST_ASSEMBLY_ARC_EXECUTABLE=tests/test_$(TEST_ASSEMBLY_ARC_NAME)
TEST_ASSEMBLY_ARC_OBJECTS=tests/test_$(TEST_ASSEMBLY_ARC_NAME).o
TEST_EXECUTABLES+=$(TEST_ASSEMBLY_ARC_EXECUTABLE)
TEST_OBJECTS+=$(TEST_ASSEMBLY_ARC_OBJECTS)
$(TEST_ASSEMBLY_ARC_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_ASSEMBLY_ARC_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)
TEST_ASSEMBLY_ARC_RUN=test_run_$(TEST_ASSEMBLY_ARC_NAME)
$(TEST_ASSEMBLY_ARC_RUN): $(TEST_ASSEMBLY_ARC_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_ASSEMBLY_ARC_RUN)

