TEST_QUEUE_SPEED_NAME=queue_speed
TEST_QUEUE_SPEED_EXECUTABLE=tests/test_$(TEST_QUEUE_SPEED_NAME)
TEST_QUEUE_SPEED_OBJECTS=tests/test.o tests/test_$(TEST_QUEUE_SPEED_NAME).o
TEST_EXECUTABLES+=$(TEST_QUEUE_SPEED_EXECUTABLE)
TEST_OBJECTS+=$(TEST_QUEUE_SPEED_OBJECTS)
$(TEST_QUEUE_SPEED_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_QUEUE_SPEED_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@
TEST_QUEUE_SPEED_RUN=test_run_$(TEST_QUEUE_SPEED_NAME)
$(TEST_QUEUE_SPEED_RUN): $(TEST_QUEUE_SPEED_EXECUTABLE)
	./$^
#TEST_RUNS+=$(TEST_QUEUE_SPEED_RUN)

