TEST_FREE_LIST_NAME=free_list
TEST_FREE_LIST_EXECUTABLE=tests/test_$(TEST_FREE_LIST_NAME)
TEST_FREE_LIST_OBJECTS=tests/test_$(TEST_FREE_LIST_NAME).o
TEST_EXECUTABLES+=$(TEST_FREE_LIST_EXECUTABLE)
TEST_OBJECTS+=$(TEST_FREE_LIST_OBJECTS)
$(TEST_FREE_LIST_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_FREE_LIST_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(CONFIG_LDFLAGS)
TEST_FREE_LIST_RUN=test_run_$(TEST_FREE_LIST_NAME)
$(TEST_FREE_LIST_RUN): $(TEST_FREE_LIST_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_FREE_LIST_RUN)

