TEST_QUEUE_NAME=queue
TEST_QUEUE_EXECUTABLE=tests/test_$(TEST_QUEUE_NAME)
TEST_QUEUE_OBJECTS=tests/test_$(TEST_QUEUE_NAME).o
TEST_EXECUTABLES+=$(TEST_QUEUE_EXECUTABLE)
TEST_OBJECTS+=$(TEST_QUEUE_OBJECTS)
$(TEST_QUEUE_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_QUEUE_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@
TEST_QUEUE_RUN=test_run_$(TEST_QUEUE_NAME)
$(TEST_QUEUE_RUN): $(TEST_QUEUE_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_QUEUE_RUN)

