TEST_RED_BLACK_TREE_NAME=red_black_tree
TEST_RED_BLACK_TREE_EXECUTABLE=tests/test_$(TEST_RED_BLACK_TREE_NAME)
TEST_RED_BLACK_TREE_OBJECTS=tests/test_$(TEST_RED_BLACK_TREE_NAME).o
TEST_EXECUTABLES+=$(TEST_RED_BLACK_TREE_EXECUTABLE)
TEST_OBJECTS+=$(TEST_RED_BLACK_TREE_OBJECTS)
$(TEST_RED_BLACK_TREE_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_RED_BLACK_TREE_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(CONFIG_LDFLAGS)
TEST_RED_BLACK_TREE_RUN=test_run_$(TEST_RED_BLACK_TREE_NAME)
$(TEST_RED_BLACK_TREE_RUN): $(TEST_RED_BLACK_TREE_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_RED_BLACK_TREE_RUN)

