TEST_SEEK_NAME=seek
TEST_SEEK_EXECUTABLE=tests/test_$(TEST_SEEK_NAME)
TEST_SEEK_OBJECTS=tests/test_$(TEST_SEEK_NAME).o
TEST_EXECUTABLES+=$(TEST_SEEK_EXECUTABLE)
TEST_OBJECTS+=$(TEST_SEEK_OBJECTS)
$(TEST_SEEK_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_SEEK_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)
TEST_SEEK_RUN=test_run_$(TEST_SEEK_NAME)
$(TEST_SEEK_RUN): $(TEST_SEEK_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_SEEK_RUN)

