TEST_RING_QUEUE_NAME=ring_queue
TEST_RING_QUEUE_EXECUTABLE=tests/test_$(TEST_RING_QUEUE_NAME)
TEST_RING_QUEUE_OBJECTS=tests/test.o tests/test_$(TEST_RING_QUEUE_NAME).o
TEST_EXECUTABLES+=$(TEST_RING_QUEUE_EXECUTABLE)
TEST_OBJECTS+=$(TEST_RING_QUEUE_OBJECTS)
$(TEST_RING_QUEUE_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_RING_QUEUE_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@
TEST_RING_QUEUE_RUN=test_run_$(TEST_RING_QUEUE_NAME)
$(TEST_RING_QUEUE_RUN): $(TEST_RING_QUEUE_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_RING_QUEUE_RUN)

