TEST_HASH_TABLE_GROUP_NAME=hash_table_group
TEST_HASH_TABLE_GROUP_EXECUTABLE=tests/test_$(TEST_HASH_TABLE_GROUP_NAME)
TEST_HASH_TABLE_GROUP_OBJECTS=tests/test.o tests/test_$(TEST_HASH_TABLE_GROUP_NAME).o
TEST_EXECUTABLES+=$(TEST_HASH_TABLE_GROUP_EXECUTABLE)
TEST_OBJECTS+=$(TEST_HASH_TABLE_GROUP_OBJECTS)
$(TEST_HASH_TABLE_GROUP_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_HASH_TABLE_GROUP_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@
TEST_HASH_TABLE_GROUP_RUN=test_run_$(TEST_HASH_TABLE_GROUP_NAME)
$(TEST_HASH_TABLE_GROUP_RUN): $(TEST_HASH_TABLE_GROUP_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_HASH_TABLE_GROUP_RUN)

