TEST_ROUTER_NAME=router
TEST_ROUTER_EXECUTABLE=tests/test_$(TEST_ROUTER_NAME)
TEST_ROUTER_OBJECTS=tests/test_$(TEST_ROUTER_NAME).o
TEST_EXECUTABLES+=$(TEST_ROUTER_EXECUTABLE)
TEST_OBJECTS+=$(TEST_ROUTER_OBJECTS)
$(TEST_ROUTER_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_ROUTER_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(CONFIG_LDFLAGS)
TEST_ROUTER_RUN=test_run_$(TEST_ROUTER_NAME)
$(TEST_ROUTER_RUN): $(TEST_ROUTER_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_ROUTER_RUN)

