TEST_BIG_MAP_NAME=big_map
TEST_BIG_MAP_EXECUTABLE=tests/test_$(TEST_BIG_MAP_NAME)
TEST_BIG_MAP_OBJECTS=tests/test_$(TEST_BIG_MAP_NAME).o
TEST_EXECUTABLES+=$(TEST_BIG_MAP_EXECUTABLE)
TEST_OBJECTS+=$(TEST_BIG_MAP_OBJECTS)
$(TEST_BIG_MAP_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_BIG_MAP_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)
TEST_BIG_MAP_RUN=test_run_$(TEST_BIG_MAP_NAME)
$(TEST_BIG_MAP_RUN): $(TEST_BIG_MAP_EXECUTABLE)
	./$^
#TEST_RUNS+=$(TEST_BIG_MAP_RUN)

