TEST_QUEUE_GROUP_NAME=queue_group
TEST_QUEUE_GROUP_EXECUTABLE=tests/test_$(TEST_QUEUE_GROUP_NAME)
TEST_QUEUE_GROUP_OBJECTS=tests/test.o tests/test_$(TEST_QUEUE_GROUP_NAME).o
TEST_EXECUTABLES+=$(TEST_QUEUE_GROUP_EXECUTABLE)
TEST_OBJECTS+=$(TEST_QUEUE_GROUP_OBJECTS)
$(TEST_QUEUE_GROUP_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_QUEUE_GROUP_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@
TEST_QUEUE_GROUP_RUN=test_run_$(TEST_QUEUE_GROUP_NAME)
$(TEST_QUEUE_GROUP_RUN): $(TEST_QUEUE_GROUP_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_QUEUE_GROUP_RUN)

