TEST_MEMORY_CACHE_NAME=memory_cache
TEST_MEMORY_CACHE_EXECUTABLE=tests/test_$(TEST_MEMORY_CACHE_NAME)
TEST_MEMORY_CACHE_OBJECTS=tests/test_$(TEST_MEMORY_CACHE_NAME).o
TEST_EXECUTABLES+=$(TEST_MEMORY_CACHE_EXECUTABLE)
TEST_OBJECTS+=$(TEST_MEMORY_CACHE_OBJECTS)
$(TEST_MEMORY_CACHE_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_MEMORY_CACHE_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(CONFIG_LDFLAGS)
TEST_MEMORY_CACHE_RUN=test_run_$(TEST_MEMORY_CACHE_NAME)
$(TEST_MEMORY_CACHE_RUN): $(TEST_MEMORY_CACHE_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_MEMORY_CACHE_RUN)

