TEST_BINARY_HEAP_NAME=binary_heap
TEST_BINARY_HEAP_EXECUTABLE=tests/test_$(TEST_BINARY_HEAP_NAME)
TEST_BINARY_HEAP_OBJECTS=tests/test_$(TEST_BINARY_HEAP_NAME).o
TEST_EXECUTABLES+=$(TEST_BINARY_HEAP_EXECUTABLE)
TEST_OBJECTS+=$(TEST_BINARY_HEAP_OBJECTS)
$(TEST_BINARY_HEAP_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_BINARY_HEAP_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(CONFIG_LDFLAGS)
TEST_BINARY_HEAP_RUN=test_run_$(TEST_BINARY_HEAP_NAME)
$(TEST_BINARY_HEAP_RUN): $(TEST_BINARY_HEAP_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_BINARY_HEAP_RUN)

