TEST_PACKER_NAME=packer
TEST_PACKER_EXECUTABLE=tests/test_$(TEST_PACKER_NAME)
TEST_PACKER_OBJECTS=tests/test_$(TEST_PACKER_NAME).o
TEST_EXECUTABLES+=$(TEST_PACKER_EXECUTABLE)
TEST_OBJECTS+=$(TEST_PACKER_OBJECTS)
$(TEST_PACKER_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_PACKER_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@
TEST_PACKER_RUN=test_run_$(TEST_PACKER_NAME)
$(TEST_PACKER_RUN): $(TEST_PACKER_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_PACKER_RUN)

