TEST_MEMORY_POOL_NAME=memory_pool
TEST_MEMORY_POOL_EXECUTABLE=tests/test_$(TEST_MEMORY_POOL_NAME)
TEST_MEMORY_POOL_OBJECTS=tests/test_$(TEST_MEMORY_POOL_NAME).o
TEST_EXECUTABLES+=$(TEST_MEMORY_POOL_EXECUTABLE)
TEST_OBJECTS+=$(TEST_MEMORY_POOL_OBJECTS)
$(TEST_MEMORY_POOL_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_MEMORY_POOL_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(CONFIG_LDFLAGS)
TEST_MEMORY_POOL_RUN=test_run_$(TEST_MEMORY_POOL_NAME)
$(TEST_MEMORY_POOL_RUN): $(TEST_MEMORY_POOL_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_MEMORY_POOL_RUN)

