TEST_FAST_QUEUE_ITERATOR_NAME=fast_queue_iterator
TEST_FAST_QUEUE_ITERATOR_EXECUTABLE=tests/test_$(TEST_FAST_QUEUE_ITERATOR_NAME)
TEST_FAST_QUEUE_ITERATOR_OBJECTS=tests/test_$(TEST_FAST_QUEUE_ITERATOR_NAME).o
TEST_EXECUTABLES+=$(TEST_FAST_QUEUE_ITERATOR_EXECUTABLE)
TEST_OBJECTS+=$(TEST_FAST_QUEUE_ITERATOR_OBJECTS)
$(TEST_FAST_QUEUE_ITERATOR_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_FAST_QUEUE_ITERATOR_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)
TEST_FAST_QUEUE_ITERATOR_RUN=test_run_$(TEST_FAST_QUEUE_ITERATOR_NAME)
$(TEST_FAST_QUEUE_ITERATOR_RUN): $(TEST_FAST_QUEUE_ITERATOR_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_FAST_QUEUE_ITERATOR_RUN)

