TEST_ASSEMBLY_VERTEX_NAME=assembly_vertex
TEST_ASSEMBLY_VERTEX_EXECUTABLE=tests/test_$(TEST_ASSEMBLY_VERTEX_NAME)
TEST_ASSEMBLY_VERTEX_OBJECTS=tests/test_$(TEST_ASSEMBLY_VERTEX_NAME).o
TEST_EXECUTABLES+=$(TEST_ASSEMBLY_VERTEX_EXECUTABLE)
TEST_OBJECTS+=$(TEST_ASSEMBLY_VERTEX_OBJECTS)
$(TEST_ASSEMBLY_VERTEX_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_ASSEMBLY_VERTEX_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(CONFIG_LDFLAGS)
TEST_ASSEMBLY_VERTEX_RUN=test_run_$(TEST_ASSEMBLY_VERTEX_NAME)
$(TEST_ASSEMBLY_VERTEX_RUN): $(TEST_ASSEMBLY_VERTEX_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_ASSEMBLY_VERTEX_RUN)

