TEST_MAP_DELETE_NAME=map_delete
TEST_MAP_DELETE_EXECUTABLE=tests/test_$(TEST_MAP_DELETE_NAME)
TEST_MAP_DELETE_OBJECTS=tests/test_$(TEST_MAP_DELETE_NAME).o
TEST_EXECUTABLES+=$(TEST_MAP_DELETE_EXECUTABLE)
TEST_OBJECTS+=$(TEST_MAP_DELETE_OBJECTS)
$(TEST_MAP_DELETE_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_MAP_DELETE_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(CONFIG_LDFLAGS)
TEST_MAP_DELETE_RUN=test_run_$(TEST_MAP_DELETE_NAME)
$(TEST_MAP_DELETE_RUN): $(TEST_MAP_DELETE_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_MAP_DELETE_RUN)

