TEST_DNA_KMER_NAME=dna_kmer
TEST_DNA_KMER_EXECUTABLE=tests/test_$(TEST_DNA_KMER_NAME)
TEST_DNA_KMER_OBJECTS=tests/test_$(TEST_DNA_KMER_NAME).o
TEST_EXECUTABLES+=$(TEST_DNA_KMER_EXECUTABLE)
TEST_OBJECTS+=$(TEST_DNA_KMER_OBJECTS)
$(TEST_DNA_KMER_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_DNA_KMER_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)
TEST_DNA_KMER_RUN=test_run_$(TEST_DNA_KMER_NAME)
$(TEST_DNA_KMER_RUN): $(TEST_DNA_KMER_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_DNA_KMER_RUN)

