TEST_RING_NAME=ring
TEST_RING_EXECUTABLE=tests/test_$(TEST_RING_NAME)
TEST_RING_OBJECTS=tests/test.o tests/test_$(TEST_RING_NAME).o
TEST_EXECUTABLES+=$(TEST_RING_EXECUTABLE)
TEST_OBJECTS+=$(TEST_RING_OBJECTS)
$(TEST_RING_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_RING_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@
TEST_RING_RUN=test_run_$(TEST_RING_NAME)
$(TEST_RING_RUN): $(TEST_RING_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_RING_RUN)

