TEST_DNA_SEQUENCE_NAME=dna_sequence
TEST_DNA_SEQUENCE_EXECUTABLE=tests/test_$(TEST_DNA_SEQUENCE_NAME)
TEST_DNA_SEQUENCE_OBJECTS=tests/test_$(TEST_DNA_SEQUENCE_NAME).o
TEST_EXECUTABLES+=$(TEST_DNA_SEQUENCE_EXECUTABLE)
TEST_OBJECTS+=$(TEST_DNA_SEQUENCE_OBJECTS)
$(TEST_DNA_SEQUENCE_EXECUTABLE): $(LIBRARY_OBJECTS) $(TEST_DNA_SEQUENCE_OBJECTS) $(TEST_LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)
TEST_DNA_SEQUENCE_RUN=test_run_$(TEST_DNA_SEQUENCE_NAME)
$(TEST_DNA_SEQUENCE_RUN): $(TEST_DNA_SEQUENCE_EXECUTABLE)
	./$^
TEST_RUNS+=$(TEST_DNA_SEQUENCE_RUN)

