
APPLICATION_ARGONNITE_PRODUCT=applications/argonnite_kmer_counter/argonnite
APPLICATION_ARGONNITE_OBJECTS=applications/argonnite_kmer_counter/argonnite.o applications/argonnite_kmer_counter/main.o

APPLICATION_EXECUTABLES+=$(APPLICATION_ARGONNITE_PRODUCT)
APPLICATION_OBJECTS+=$(APPLICATION_ARGONNITE_OBJECTS)

$(APPLICATION_ARGONNITE_PRODUCT): $(APPLICATION_ARGONNITE_OBJECTS) $(LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(CONFIG_LDFLAGS)

