#!/bin/bash
#PBS -N __JOB__
#PBS -A m1523
#PBS -l walltime=3:00:00
#PBS -l mppwidth=6144
#PBS -q regular

# 256 * 24 = 6144

cd $PBS_O_WORKDIR
export MPICH_NEMESIS_ASYNC_PROGRESS=1
export MPICH_MAX_THREAD_SAFETY=multiple
export CRAY_MALLOPT_OFF=1

echo "Commit= __COMMIT__"

aprun -n 256 -N 1 -d 23 -r 1 \
              ./__JOB__.__APP__ -threads-per-node 23 -print-thorium-data \
              -k 27 __SAMPLE__/*.fastq -o __JOB__ > __JOB__.stdout

