#!/bin/bash
#PBS -N __JOB__
#PBS -A CI-DEB000002
#PBS -l walltime=1:00:00
#PBS -l mppwidth=4096

#irb(main):002:0> 128 * 32
# => 4096

cd $PBS_O_WORKDIR
export MPICH_NEMESIS_ASYNC_PROGRESS=1
export MPICH_MAX_THREAD_SAFETY=multiple
export CRAY_MALLOPT_OFF=1

echo "App= __APP__"
echo "Job= __JOB__"
echo "Commit= __COMMIT__"

aprun -n 128 -N 1 -d 31 -r 1 \
              __JOB__.__APP__ -threads-per-node 31 -print-thorium-data

