#!/bin/bash
#PBS -N __JOB__
#PBS -A __ALLOCATION__
#PBS -l walltime=__WALLTIME__
#PBS -l mppwidth=__THREADS__
#PBS -q __QUEUE__

cd $PBS_O_WORKDIR
#export MPICH_NEMESIS_ASYNC_PROGRESS=1
#export MPICH_MAX_THREAD_SAFETY=multiple
#export CRAY_MALLOPT_OFF=1

echo "Commit= __COMMIT__"

aprun -n __NODES__ -N 1 -d 32 \
              __JOB__.__APP__ -threads-per-node 32 \
              -print-thorium-data \
              -k 27 __SAMPLE__/*.fastq \
              -o __JOB__ \
             -minimum-coverage 2 \

