EXAMPLE_PING_PONG_OBJECTS=examples/ping_pong/hello.o examples/ping_pong/main.o
EXAMPLE_PING_PONG_EXECUTABLE=examples/ping_pong/ping_pong

$(EXAMPLE_PING_PONG_EXECUTABLE): $(EXAMPLE_PING_PONG_OBJECTS) $(LIBRARY_OBJECTS)
	$(Q)$(ECHO) "  LD $@"
	$(Q)$(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS) $(CONFIG_LDFLAGS)

EXAMPLE_EXECUTABLES += $(EXAMPLE_PING_PONG_EXECUTABLE)
EXAMPLE_OBJECTS += $(EXAMPLE_PING_PONG_OBJECTS)

